import React, { createContext, useContext, useState } from 'react'

const translations = {
  AR: {
    admin_dashboard: "لوحة التحكم",
    admin_overview: "نظرة عامة",
    admin_users: "المستخدمون",
    admin_pending: "قيد الانتظار",
    admin_messages: "الرسائل",
    admin_societes: "الشركات",
    admin_companies: "الشركات",
    admin_settings: "الإعدادات",
    admin_approve: "موافقة",
    admin_reject: "رفض",
    admin_delete: "حذف",
    admin_confirm: "تأكيد؟",
    admin_yes: "نعم",
    admin_no: "لا",
    admin_total_users: "إجمالي المستخدمين",
    admin_pending_label: "قيد الانتظار",
    admin_action_required: "إجراء مطلوب",
    admin_approved: "موافق عليه",
    admin_rejected: "مرفوض",
    admin_search_users: "البحث بالاسم أو البريد...",
    admin_all: "الكل",
    admin_back_site: "→ العودة للموقع",
    admin_no_pending: "لا يوجد مستخدمون في الانتظار",
    admin_no_pending_sub: "تمت معالجة جميع الحسابات.",
    admin_recent_activity: "النشاط الأخير",
    admin_user_distribution: "توزيع المستخدمين",
    admin_search_placeholder: "البحث بالاسم أو البريد...",
    admin_user: "المستخدم",
    admin_email: "البريد الإلكتروني",
    admin_status: "الحالة",
    admin_companies_count: "الشركات",
    admin_registered: "تاريخ التسجيل",
    admin_actions: "الإجراءات",
    admin_view: "عرض",
    admin_if: "المعرف الضريبي",
    admin_ice: "ICE",
    admin_city: "المدينة",
    admin_settings_title: "الإعدادات",
    admin_toggle_lang: "اللغة",
    users: "المستخدمون",
    pending: "قيد الانتظار",
    messages: "الرسائل",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    manage_users: "إدارة جميع المستخدمين",
    add_user: "إضافة مستخدم",
    edit_user: "تعديل",
    new_user: "إضافة مستخدم جديد",
    full_name: "الاسم الكامل",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    status: "الحالة",
    role: "الدور",
    create: "إنشاء",
    save: "حفظ",
    cancel: "إلغاء",
    update: "تحديث",
    change_password: "تغيير كلمة المرور",
    current_password: "كلمة المرور الحالية",
    new_password: "كلمة المرور الجديدة",
    confirm_password: "تأكيد كلمة المرور",
    preferences: "التفضيلات",
    theme: "المظهر",
    language: "اللغة",
    light_mode: "الوضع الفاتح",
    dark_mode: "الوضع الداكن",
    dashboard: "لوحة التحكم",
    companies: "الشركات",
    pending_approval: "في انتظار الموافقة",
    approve_reject: "الموافقة أو الرفض على المستخدمين",
    contact_messages: "رسائل التواصل",
    manage_account: "إدارة حسابك",
    user_evolution: "تطور التسجيلات",
    user_distribution: "توزيع المستخدمين",
    hello_admin: "مرحباً، المسؤول",
    platform_info: "إليك ما يحدث على منصتك",
    total_users_label: "المستخدمون",
    this_month: "هذا الشهر",
    action_required: "إجراء مطلوب",
    up_to_date: "محدث",
    companies_label: "الشركات",
    average: "متوسط",
    messages_label: "الرسائل",
    approved_label: "موافق عليه",
    rejected_label: "مرفوض",
    average_companies: "متوسط الشركات",
    active_user_label: "آخر مستخدم",
    no_messages: "لا توجد رسائل",
    mark_as_read: "تعيين كمقروء",
    admin_profile: "ملف المسؤول",
    search_placeholder: "بحث...",
    all_status: "الكل",
    user_label: "المستخدم",
    email_label: "البريد الإلكتروني",
    status_label: "الحالة",
    registered_label: "تاريخ التسجيل",
    actions_label: "الإجراءات",
    approve: "موافقة",
    reject: "رفض",
    pending_users: "قيد الانتظار",
    unread: "غير مقروءة",
    no_pending: "لا يوجد مستخدمون في الانتظار",
    no_users: "لا يوجد مستخدمون",
    loading: "جاري التحميل...",
    delete_user: "حذف",
    confirm_delete: "تأكيد الحذف",
    enter_name: "أدخل الاسم الكامل",
    enter_email: "أدخل البريد الإلكتروني",
    enter_password: "أدخل كلمة مرور آمنة",
    approved: "موافق عليه",
    new_users_month: "المستخدمون الجدد",
    user_approved: "تمت الموافقة على المستخدم",
    user_rejected: "تم رفض المستخدم",
    user_updated: "تم تحديث المستخدم",
    user_created: "تم إنشاء المستخدم بنجاح",
    user_deleted: "تم حذف المستخدم",
    users_companies: "المستخدمون والشركات",
    no_data_found: "لم يتم العثور على بيانات",
    no_users_with_companies: "لم يتم العثور على مستخدمين لديهم شركات",
    user_role: "مستخدم",
    admin_role: "مسؤول",
    close: "إغلاق",
    edit_user_title: "تعديل المستخدم",
    saving: "جاري الحفظ...",
    last_registration: "آخر تسجيل",
    none: "لا يوجد",
    error_loading_companies: "خطأ في تحميل الشركات",
    declarations_managed_info: "يتم إدارة الإقرارات مباشرة من قبل المستخدمين في حساباتهم.",
    read: "مقروء",
    manage_companies_by_user: "إدارة الشركات حسب المستخدم",
    search_user_company_if_ice: "البحث بالمستخدم، الشركة، IF أو ICE...",
    most_recent: "الأحدث",
    oldest: "الأقدم",
    name_az: "الاسم (أ-ي)",
    action: "إجراء",
    view: "عرض",
    companies_with_count: "الشركات ({{count}})",
    no_companies_found: "لم يتم العثور على شركات",
    no_users_found: "لم يتم العثور على مستخدمين",
    tax_id_if: "المعرف الضريبي (IF)",
    ice_code: "رمز ICE",
    factures: "الفواتير",
    factures_overview: "نظرة عامة على جميع الفواتير على المنصة",
    total_factures: "إجمالي الفواتير",
    declarations: "الإقرارات",
    users_count: "المستخدمون",
    search: "بحث...",
    all_years: "كل السنوات",
    all_months: "كل الأشهر",
    all_regimes: "كل الأنظمة",
    monthly: "شهري",
    quarterly: "ربع سنوي",
    user: "المستخدم",
    company: "الشركة",
    nb_invoices: "عدد الفواتير",
    last_date: "آخر تاريخ",
    declaration_number: "رقم الإقرار",
    regime: "النظام",
    date: "التاريخ",
    export_excel: "تصدير Excel",
    no_invoices_found: "لم يتم العثور على فواتير",
    loading_invoices: "جاري تحميل الفواتير...",
  },
  FR: {
    admin_dashboard: "Tableau de bord",
    admin_overview: "Vue d'ensemble",
    admin_users: "Utilisateurs",
    admin_pending: "En attente",
    admin_messages: "Messages",
    admin_societes: "Sociétés",
    admin_companies: "Sociétés",
    admin_settings: "Paramètres",
    admin_approve: "Approuver",
    admin_reject: "Rejeter",
    admin_delete: "Supprimer",
    admin_confirm: "Confirmer ?",
    admin_yes: "Oui",
    admin_no: "Non",
    admin_total_users: "UTILISATEURS TOTAL",
    admin_pending_label: "EN ATTENTE",
    admin_action_required: "Action requise",
    admin_approved: "Approuvé",
    admin_rejected: "Rejeté",
    admin_search_users: "Rechercher par nom, email...",
    admin_all: "Tous",
    admin_back_site: "← Retour au site",
    admin_no_pending: "Aucun utilisateur en attente",
    admin_no_pending_sub: "Tous les comptes ont été traités.",
    admin_recent_activity: "Activité récente",
    admin_user_distribution: "Répartition utilisateurs",
    admin_search_placeholder: "Rechercher par nom, email...",
    admin_user: "UTILISATEUR",
    admin_email: "EMAIL",
    admin_status: "STATUT",
    admin_companies_count: "SOCIÉTÉS",
    admin_registered: "INSCRIPTION",
    admin_actions: "ACTIONS",
    admin_view: "Afficher",
    admin_if: "IF",
    admin_ice: "ICE",
    admin_city: "VILLE",
    admin_settings_title: "Paramètres",
    admin_toggle_lang: "Langue",
    users: "Utilisateurs",
    pending: "En attente",
    messages: "Messages",
    settings: "Paramètres",
    logout: "Déconnexion",
    manage_users: "Gérez tous les utilisateurs du système",
    add_user: "Ajouter utilisateur",
    edit_user: "Modifier",
    new_user: "Ajouter un nouvel utilisateur",
    full_name: "Nom complet",
    email: "Email",
    password: "Mot de passe",
    status: "Statut",
    role: "Rôle",
    create: "Créer",
    save: "Enregistrer",
    cancel: "Annuler",
    update: "Mettre à jour",
    change_password: "Changer le mot de passe",
    current_password: "Mot de passe actuel",
    new_password: "Nouveau mot de passe",
    confirm_password: "Confirmer mot de passe",
    preferences: "Préférences",
    theme: "Thème",
    language: "Langue",
    light_mode: "Passer au mode clair",
    dark_mode: "Passer au mode sombre",
    dashboard: "Tableau de bord",
    companies: "Sociétés",
    pending_approval: "En attente d'approbation",
    approve_reject: "Approuvez ou rejetez les utilisateurs",
    contact_messages: "Messages de contact des utilisateurs",
    manage_account: "Gérez votre compte administrateur",
    user_evolution: "Évolution des inscriptions",
    user_distribution: "Répartition utilisateurs",
    approved: "Approuvés",
    rejected: "Rejetés",
    enter_name: "Entrer le nom complet",
    enter_email: "Entrer l'adresse email",
    enter_password: "Entrer un mot de passe sécurisé",
    hello_admin: "Bonjour, Admin",
    platform_info: "Voici ce qui se passe sur votre plateforme",
    total_users_label: "Utilisateurs",
    this_month: "ce mois",
    pending_users: "En attente",
    action_required: "Action requise",
    up_to_date: "À jour",
    companies_label: "Sociétés",
    average: "moy",
    messages_label: "Messages",
    unread: "Non lus",
    approved_label: "Approuvés",
    rejected_label: "Rejetés",
    average_companies: "Moyenne sociétés",
    active_user_label: "Utilisateur actif",
    no_pending: "Aucun utilisateur en attente",
    no_messages: "Aucun message",
    mark_as_read: "Marquer comme lu",
    admin_profile: "Profil administrateur",
    no_users: "Aucun utilisateur",
    search_placeholder: "Rechercher...",
    all_status: "Tous",
    user_label: "Utilisateur",
    email_label: "Email",
    status_label: "Statut",
    registered_label: "Inscrit le",
    actions_label: "Actions",
    loading: "Chargement...",
    delete_user: "Supprimer",
    confirm_delete: "Confirmer la suppression",
    approve: "Approuver",
    new_users_month: "NOUVEAUX UTILISATEURS",
    user_approved: "Utilisateur approuvé",
    user_rejected: "Utilisateur rejeté",
    user_updated: "Utilisateur mis à jour",
    user_created: "Utilisateur créé avec succès",
    user_deleted: "Utilisateur supprimé",
    users_companies: "Utilisateurs & Sociétés",
    no_data_found: "Aucune donnée trouvée",
    no_users_with_companies: "Aucun utilisateur avec des sociétés n'a été trouvé",
    user_role: "Utilisateur",
    admin_role: "Administrateur",
    close: "Fermer",
    edit_user_title: "Modifier l'utilisateur",
    saving: "Enregistrement...",
    last_registration: "Dernière inscription",
    none: "Aucun",
    error_loading_companies: "Erreur lors du chargement des sociétés",
    declarations_managed_info: "Les déclarations sont gérées directement par les utilisateurs dans leurs comptes respectifs.",
    read: "Lu",
    manage_companies_by_user: "Gestion des sociétés par utilisateur",
    search_user_company_if_ice: "Rechercher par utilisateur, société, IF ou ICE...",
    most_recent: "Plus récentes",
    oldest: "Plus anciennes",
    name_az: "Nom (A-Z)",
    action: "Action",
    view: "Voir",
    companies_with_count: "Sociétés ({{count}})",
    no_companies_found: "Aucune société trouvée",
    no_users_found: "Aucun utilisateur trouvé",
    tax_id_if: "IF (Identifiant Fiscal)",
    ice_code: "ICE",
    factures: "Factures",
    factures_overview: "Vue globale de toutes les factures sur la plateforme",
    total_factures: "TOTAL FACTURES",
    declarations: "DÉCLARATIONS",
    users_count: "UTILISATEURS",
    search: "Rechercher...",
    all_years: "Toutes les années",
    all_months: "Tous les mois",
    all_regimes: "Tous les régimes",
    monthly: "Mensuel",
    quarterly: "Trimestriel",
    user: "Utilisateur",
    company: "Société",
    nb_invoices: "Nb Factures",
    last_date: "Dernière Date",
    declaration_number: "N° Déclaration",
    regime: "Régime",
    date: "Date",
    export_excel: "⬇️ Export Excel",
    no_invoices_found: "Aucune facture trouvée",
    loading_invoices: "Chargement...",
  },
  EN: {
    admin_dashboard: "Dashboard",
    admin_overview: "Overview",
    admin_users: "Users",
    admin_pending: "Pending",
    admin_messages: "Messages",
    admin_societes: "Companies",
    admin_companies: "Companies",
    admin_settings: "Settings",
    admin_approve: "Approve",
    admin_reject: "Reject",
    admin_delete: "Delete",
    admin_confirm: "Confirm?",
    admin_yes: "Yes",
    admin_no: "No",
    admin_total_users: "TOTAL USERS",
    admin_pending_label: "PENDING",
    admin_action_required: "Action required",
    admin_approved: "Approved",
    admin_rejected: "Rejected",
    admin_search_users: "Search by name, email...",
    admin_all: "All",
    admin_back_site: "← Back to site",
    admin_no_pending: "No pending users",
    admin_no_pending_sub: "All accounts have been processed.",
    admin_recent_activity: "Recent activity",
    admin_user_distribution: "User distribution",
    admin_search_placeholder: "Search by name, email...",
    admin_user: "USER",
    admin_email: "EMAIL",
    admin_status: "STATUS",
    admin_companies_count: "COMPANIES",
    admin_registered: "REGISTERED",
    admin_actions: "ACTIONS",
    admin_view: "View",
    admin_if: "IF",
    admin_ice: "ICE",
    admin_city: "CITY",
    admin_settings_title: "Settings",
    admin_toggle_lang: "Language",
    users: "Users",
    pending: "Pending",
    messages: "Messages",
    settings: "Settings",
    logout: "Logout",
    manage_users: "Manage all system users",
    add_user: "Add User",
    edit_user: "Edit",
    new_user: "Add New User",
    full_name: "Full Name",
    email: "Email",
    password: "Password",
    status: "Status",
    role: "Role",
    create: "Create",
    save: "Save",
    cancel: "Cancel",
    update: "Update",
    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    preferences: "Preferences",
    theme: "Theme",
    language: "Language",
    light_mode: "Switch to Light Mode",
    dark_mode: "Switch to Dark Mode",
    dashboard: "Dashboard",
    companies: "Companies",
    pending_approval: "Pending Approval",
    approve_reject: "Approve or reject users",
    contact_messages: "User Contact Messages",
    manage_account: "Manage your admin account",
    user_evolution: "User Registration Evolution",
    user_distribution: "User Distribution",
    approved: "Approved",
    rejected: "Rejected",
    enter_name: "Enter full name",
    enter_email: "Enter email address",
    enter_password: "Enter a secure password",
    hello_admin: "Hello, Admin",
    platform_info: "Here's what's happening on your platform",
    total_users_label: "Users",
    this_month: "this month",
    pending_users: "Pending",
    action_required: "Action required",
    up_to_date: "Up to date",
    companies_label: "Companies",
    average: "avg",
    messages_label: "Messages",
    unread: "Unread",
    approved_label: "Approved",
    rejected_label: "Rejected",
    average_companies: "Average companies",
    active_user_label: "Active user",
    no_pending: "No pending users",
    no_messages: "No messages",
    mark_as_read: "Mark as read",
    admin_profile: "Admin Profile",
    no_users: "No users",
    search_placeholder: "Search...",
    all_status: "All",
    user_label: "User",
    email_label: "Email",
    status_label: "Status",
    registered_label: "Registered",
    actions_label: "Actions",
    loading: "Loading...",
    delete_user: "Delete",
    confirm_delete: "Confirm deletion",
    approve: "Approve",
    new_users_month: "NEW USERS",
    user_approved: "User approved",
    user_rejected: "User rejected",
    user_updated: "User updated",
    user_created: "User created successfully",
    user_deleted: "User deleted",
    users_companies: "Users & Companies",
    no_data_found: "No data found",
    no_users_with_companies: "No users with companies found",
    user_role: "User",
    admin_role: "Administrator",
    close: "Close",
    edit_user_title: "Edit User",
    saving: "Saving...",
    last_registration: "Last registration",
    none: "None",
    error_loading_companies: "Error loading companies",
    declarations_managed_info: "Declarations are managed directly by users in their respective accounts.",
    read: "Read",
    manage_companies_by_user: "Manage companies by user",
    search_user_company_if_ice: "Search by user, company, IF or ICE...",
    most_recent: "Most Recent",
    oldest: "Oldest",
    name_az: "Name (A-Z)",
    action: "Action",
    view: "View",
    companies_with_count: "Companies ({{count}})",
    no_companies_found: "No companies found",
    no_users_found: "No users found",
    tax_id_if: "Tax ID (IF)",
    ice_code: "ICE Code",
    factures: "Invoices",
    factures_overview: "Global view of all invoices on the platform",
    total_factures: "TOTAL INVOICES",
    declarations: "DECLARATIONS",
    users_count: "USERS",
    search: "Search...",
    all_years: "All years",
    all_months: "All months",
    all_regimes: "All regimes",
    monthly: "Monthly",
    quarterly: "Quarterly",
    user: "User",
    company: "Company",
    nb_invoices: "Nb Invoices",
    last_date: "Last Date",
    declaration_number: "Declaration #",
    regime: "Regime",
    date: "Date",
    export_excel: "⬇️ Export Excel",
    no_invoices_found: "No invoices found",
    loading_invoices: "Loading...",
  }
}

const AdminLanguageContext = createContext()

export function AdminLanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('adminLanguage') || 'FR'
  })

  React.useEffect(() => {
    document.documentElement.dir = language === 'AR' ? 'rtl' : 'ltr'
    document.documentElement.lang = language === 'AR' ? 'ar' : language === 'FR' ? 'fr' : 'en'
  }, [language])

  const t = (key, params = {}) => {
    let text = translations[language]?.[key] || translations['FR'][key] || key
    // Replace parameters in the translation string
    Object.entries(params).forEach(([paramKey, paramValue]) => {
      text = text.replace(new RegExp(`\\{\\{${paramKey}\\}\\}`, 'g'), paramValue)
    })
    return text
  }

  const toggleLanguage = () => {
    const langs = ['FR', 'EN', 'AR']
    const currentIndex = langs.indexOf(language)
    const newLang = langs[(currentIndex + 1) % langs.length]
    setLanguage(newLang)
    localStorage.setItem('adminLanguage', newLang)
  }

  return (
    <AdminLanguageContext.Provider value={{ language, t, toggleLanguage }}>
      {children}
    </AdminLanguageContext.Provider>
  )
}

export function useAdminLanguage() {
  const context = useContext(AdminLanguageContext)
  if (!context) {
    throw new Error('useAdminLanguage must be used within AdminLanguageProvider')
  }
  return context
}
